name: openldap
version: '2.4.45'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode

apps:
  slapd:
    command: bin/slapd-init start
    stop-command: bin/slapd-init stop
    daemon: forking
    plugs: [network, network-bind, mount-observe, home, removable-media]

parts:
  openldap:
    plugin: autotools
    source: ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-2.4.45.tgz
    build-packages:
      - libdb5.3
      - libdb5.3-dev 
      - libdb5.3-dbg
    snap:
     - -etc/openldap/slapd.ldif
  environment:
        plugin: dump
        source: .
        organize:
            slapd.ldif: etc/openldap/
            core.ldif: etc/openldap/
            slapd-init: bin/
        after: [openldap]
