version: 2
jobs:
  build:
    docker:
      - image: buggtb/circleci-snapcraft

    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_remote_docker 
      - run: apt -y update
      - run: /run.sh