version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: buggtb/circleci-snapcraft
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      
    
    steps:
      - checkout

      #- setup_remote_docker 
       
      # run tests!
